### ISSUE TITLE
Use assigned wallet, not any hardcoded default

### ISSUE THREAD

**Issue by CrafBug** [F1ash/kde-plasma-mail-checker#7]
PlasmaMailChecker 1.1.10 attempt to open "kdewallet" and to save settings in "kdewallet". This wallet is existing on my computer, but closed and not used. 

In KDE (version 4.7.0) in systemsettings I have selected another wallet to be used generally. I expect, PlasmaMailChecker should ask KDE, which wallet is to be opened and is to be used, but PlasmaMailChecker is using the KDE default wallet.

**Comment by F1ash** [comment]
This is the right note. I'll do it when I have spare time.

**Comment by F1ash** [comment]
I`m fixed the using of default (local) wallet. Test it , please.

**Comment by CrafBug** [comment]
I have uninstalled version  1.1.10 and additionally removed configuration files in ~/.config/plasmaMailChecker and ~/.kde/share/apps/kde-plasma-mail-checker/kde-plasma-mail-checker.notifyrc.

After adding M@ilChecker 1.1.12 it tried to open kdewallet instead of my selected wallet again. 
Then I have removed the unused kdewallet file from my wallet. After KDE restart the M@ilChecker tried to create a new kdewallet. 

I suspect, your bugfix was not successful.

**Comment by F1ash** [comment]
This is very strange, because in KDE4.6.5 works correctly. Then, kdewallet a default wallet, may be it can not be removed. But you can choose to use another wallet as default or the use an alternative wallet for local passwords. 

In this version, M@ilChecker uses default wallet or an alternative, if specified.

I do not want to assume that the plasmoid is not installed correctly, but try to make sure that the code is changed.
In ~/.kde/share/apps/plasma/plasmoids/kde-plasma-mail-checker/contents/code/main.py str.900 :
         self.wallet = KWallet.Wallet.openWallet(KWallet.Wallet.LocalWallet(), 0)

**Comment by CrafBug** [comment]
The main.py in the downloaded kde-plasma-mail-checker-1.1.12.tar.bz2 and also the main.py file in .kde path is containing at line 900 the code:
self.wallet = KWallet.Wallet.openWallet('kdewallet', 0)

**Comment by CrafBug** [comment]
I have downloaded the kde-plasma-mail-checker-1.1.12.tar.bz2 again and found the content is changed. I will test it tomorrow.
